### PR TITLE
Including the digital current measurement for each-roc

### PR DESCRIPTION
**Pull request by andreavargas**
Dear all,

for the BareModule section, it is needed the measurement of the digital current. This measurement is performed for -each- roc and not for the whole module (as it is in the FullModule section). 
Do you know - who implemented the DigitalCurrent module in Fulltest? I just would like that he/she had a look to the section DigChipCurrent.  
That numbers are needed to fill a table which is used for DB upload, that's why I had to change the Summary1 in BareModule section as well.

please let me know if this is ok
thanks for your help,

Cheers
Andrea

### CODE REVIEW

**Comment by macjohnny** [comment]
@veloxid do you know who is responsible for this?

**Comment by andreavargas** [comment]
Dear all,

would be possible to merge this changes? The included routine do the 
same as the one which exist in the full module section, the difference 
is just that the displayed current is for each chip and not for the 
whole module (since for baremodule we test chip by chip).

I am asking, since I know that some of our collegues would like to use 
it, to produce the needed tables to upload their -baremodule- 
tests-results into the DB.

thanks for your help!
Cheers

Andrea

**Comment by macjohnny** [comment]
hey andrea
did you test the changes? if so, I can merge them.
please open a new issue for the db-upload.

**Comment by andreavargas** [comment]
Dear Esteban,

yes yes I check it, if possible please merge it.

what do you mean with to open a new issue for the db-upload? I think 
that after merging then we are complete with the tables for DB upload. 
In the baremodule section just tables are produced and the DB team uses 
it to fill the DB entries.

Thanks for your feedback!
Cheers,
Andrea

**Comment by macjohnny** [comment]
ok, good.

**Pull request merged**
