### PR TITLE
Issue #66: IV curve in central DB for FullTest and XRay

### PR DESCRIPTION
**Pull request by macjohnny**

### CODE REVIEW

**Comment by macjohnny** [comment]
@tommasoboccali @arizzi 
ciao
please confirm that the iv curve integration is complete and working. if so, i will merge this pull request into master.

**Comment by tommasoboccali** [comment]
i need to push modifications for Fulltest.py (CustomWriteToDB).
It is probably better if you push in the master, and then I push these.

so, go ahead

tom

On Tue, May 26, 2015 at 12:15 PM, Esteban Marín <notifications@github.com>
wrote:

> @tommasoboccali <https://github.com/tommasoboccali> @arizzi
> <https://github.com/arizzi>
> ciao
> please confirm that the iv curve integration is complete and working. if
> so, i will merge this pull request into master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi46/MoReWeb/pull/76#issuecomment-105477534>.
>



-- 
Tommaso Boccali
INFN Pisa

**Comment by macjohnny** [comment]
@tommasoboccali would you mind pushing your changes to macjohnny-dev-ivcurve first, so that we can have one final pull request to master?

**Comment by tommasoboccali** [comment]
ciao, unfortunately attending a workshop for the whole week, i cannot do
the final check i was willing to

let me see if I find a way...

tom

On Tue, May 26, 2015 at 12:30 PM, Esteban Marín <notifications@github.com>
wrote:

> @tommasoboccali <https://github.com/tommasoboccali> would you mind
> pushing your changes to macjohnny-dev-ivcurve first, so that we can have
> one final pull request to master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi46/MoReWeb/pull/76#issuecomment-105482784>.
>



-- 
Tommaso Boccali
INFN Pisa

**Comment by macjohnny** [comment]
@tommasoboccali i merged your changes into my branch. please do the final check and let me know if everything works, so that i can merge it into master.

**Comment by tommasoboccali** [comment]
seems ok to me

http://cmspixelprod.pi.infn.it/data/pixels/t0logs/2015-05-26//27195

tom

On Tue, May 26, 2015 at 3:57 PM, Esteban Marín <notifications@github.com>
wrote:

> @tommasoboccali <https://github.com/tommasoboccali> i merged your changes
> into my branch. please do the final check and let me know if everything
> works, so that i can merge it into master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi46/MoReWeb/pull/76#issuecomment-105533977>.
>



-- 
Tommaso Boccali
INFN Pisa

**Pull request merged**
