### PR TITLE
Include now json files of defect pixels and txt files needed for later D...

### PR DESCRIPTION
**Pull request by andreavargas**
Few routines have changed to write json files with dead/missing pixels coming from 
BumpBonding and PixelAlive tests
In Summaryv1 additional subdirectories are created to store the output test results. Such structure is
suitable to upload the results to the DB afterwards.

### CODE REVIEW

**Comment by macjohnny** [comment]
hey andrea
looks good.
one remark: the db-interface is implemented in such a way that it gets the data directly from the objects, without the need for the json-files. in this case you could place the data in self.ResultData['HiddenData'] to be accessible. or do you intend to do something else with the json-files?

**Comment by andreavargas** [comment]
Dear Esteban,

yes, the present situation is that the DB team will not run moreweb  to 
upload directly the baremodule tests results. Each center will then have 
to upload the tests results files with a given subdirectory and file 
structure.

This is the reason why I try to implement the needed files and wrote 
those json files into an additional output subdirectory (inside 
Summaryv1). The idea is that each user at the end of running MoReWeb can 
look at the output and then he/she can just tar the output directory and 
send it to DB team. The json files have to look like "{"ROC12": 
[[1,11]],"ROC6": [[28,65]],"ROC0": [[8,79]],"ROC2": [[17,11]]}" and have 
a fix name.

I am still disscussing other tests and by sure I have to include some 
more files, but I hope this implementation is ok for you. Please let me 
know ....

Cheers,
Andrea

**Comment by macjohnny** [comment]
hi andrea
in that case i totally agree with your implementation.
please also note that there json files generated automatically for all data in self.ResultData['KeyValueDictPairs']. This could be extended to the HiddenData section, so you don't have to generate it manually.
but for the moment i think it's fine.

**Comment by andreavargas** [comment]
hi Sebastian,

thanks. I will have a look later to this 
self.ResultData['KeyValueDictPairs'] section, but for the moment, would 
be possible then merge the changes?

Cheers,
Andrea

**Pull request merged**
