### PR TITLE
Include BB2 from BareModuleTest section to FullTest

### PR DESCRIPTION
**Pull request by andreavargas**
Dear all,

I would like to include the Bump Bonding method "PixTestBB2Map from pXar" for finding missing bumps into the Fulltest section of MoReWeb. The included routines are already been used in the BareModule section of  MoReWeb.
 
The BumpBonding method used for the grading is not working optimal for some of - our - modules, please see as example the plot in the attchment - where we should compare the distributions 
"Bump Bonding C1" coming from BumpBondingProblems with
"Bare BBWidth C1" coming from BareBBWidth
we observe the same missing bumps using Xrays.

Until now I have included the distributions, but I believe more changes are necessary for the summary and grading. 

Please let me know your opinion,
Best Wishes,

Andrea

morewebfulltestbb2

### CODE REVIEW

**Comment by piberger** [comment]
Hi,

I thinks it's good to also have BB2 test in FullQualifications analyzed by MoReWeb.

What probably needs to be done:
- hide the BB2 tests if no BB2 test has been done, see https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/BB4/BB4.py#L58 for how it has been done for BB4 test
- decide in grading which BB test to take, see https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/Grading/Grading.py#L64 for BB4 test


At the moment is just looks for a BB4 test and if none if found it takes the BB test. I don't know what we should do if BB4 and BB2 test are present (if this situation will occur at all...)

**Comment by andreavargas** [comment]
Hi,

thanks for your answer! I am working on the changes. I will let you know 
as soon as I am ready,

Cheers,
Andrea

**Comment by andreavargas** [comment]
Dear Pirmin,

I include now in my brach the changes which you recommended

On 09/10/2015 06:41 PM, piberger wrote:
>
> What probably needs to be done:
>
>   * hide the BB2 tests if no BB2 test has been done, see
>     https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/BB4/BB4.py#L58
>     for how it has been done for BB4 test
>
lines were include in the 3 routines of BB2

>   * decide in grading which BB test to take, see
>     https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/Grading/Grading.py#L64
>     for BB4 test
>
> At the moment is just looks for a BB4 test and if none if found it 
> takes the BB test. I don't know what we should do if BB4 and BB2 test 
> are present (if this situation will occur at all...)
>
yes I do not know if that situation will occur. Until now it will look 
for BB4 if it is not present then will try with BB2 and if no present 
then it will take the standard bumpbonding test. I check that it works - 
no having bb2/bb4 histograms -
Please have a look at the included lines in 
Fulltest/Chips/Chip/Grading/Grading.py 
<https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/Grading/Grading.py#L64> 
- may be there is a more elegant way of to use "try".

I also had to change the routine:
  TestResultClasses/CMSPixel/QualificationGroup/Fulltest/BumpBondingMap/BumpBondingMap.py
such that BB2 is displayed for the module

Please let me know if I miss something ...
Thanks!
Cheers,

Andrea

**Comment by piberger** [comment]
Hi,

looks good, I propose to make one small change:
- do the decision between bb4, bb2 only once and then use it consistently. (Now it could be that map is taken from one and grading from the other if both are there)

I already changed this locally and will merge it if these changes are ok for you.

**Comment by piberger** [comment]
I will merge the PR already now, we can still change it later if we need to adjust details.

**Comment by andreavargas** [comment]
sure, I did not realize that could be inconsistent. Thanks for fixing it!
Cheers,

Andrea

**Pull request merged**
